---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role discovery
#
# Overview: This role's tasks come from edx_django_service.
#
#
# Dependencies:
#
#
# Example play:
#
#
- name: create web-writable journal data dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ common_web_user }}"
    group: "{{ journals_user }}"
    mode: "0775"
  with_items:
    - "{{ JOURNALS_MEDIA_ROOT }}"
  tags:
    - install
    - install:base

- name: build elasticsearch5 image
  docker_image:
     path: /edx/app/edx_ansible/edx_ansible/playbooks/roles/journals/tasks/
     name: elasticsearch5
     state: present
     nocache: yes
     force: yes

- name: create docker container
  docker_container:
    name: elasticsearch5
    image: elasticsearch5
    state: started
    ports:
     - "9500:9200"

- name: update journal elasticsearch index
  shell: >
    {{ COMMON_BIN_DIR }}/python.journals {{ COMMON_BIN_DIR }}/manage.journals update_index
  become_user: "{{ journals_user }}"
  environment: "{{ journals_environment }}"
